
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: true,
    FIREBASE_API_KEY: 'AIzaSyBiBcN3svwTQk_jOdfVz239d0zZX4FKthE'
  };
